#pragma once
#include <stdint.h>

const uint16_t SUCCESS = 0, SOCKET_FAILURE = 1, CONNECTION_FAILURE = 2,
		DISCONNECTED = 3, SHUTDOWN = 4, COMMUNICATION_ERROR = 5,
		PARAMETER_ERROR = 6, BIND_FAILURE = 7, SETUP_FAILURE = 8,
		SERVER_FULL = 9, OPT_FAILURE = 10;

const uint16_t MAXBUFFERSIZE = 512;